name: mlgeo_sk
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - pyarrow
  - matplotlib
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - nbgitpuller
  - wget
  - pooch
  - pytorch
  - torchvision
  - torchinfo
  - pip=20
